# ~/.config/alacritty/alacritty.toml

[font]
normal.family = "Ubuntu Mono"
size = 16

[window]
padding.x = 20
padding.y = 20
opacity = 0.9

[colors]
primary.foreground = "#e4e4e4"
primary.background = "#1e1e1e"

cursor.text = "#2a2a2a"
cursor.cursor = "#F44336"

selection.text = "#e4e4e4"
selection.background = "#2d2d2d"

[colors.normal]
black = "#2d2d2d"
red = "#F44336"
green = "#afaf87"
yellow = "#d8af5f"
blue = "#87afaf"
magenta = "#af87af"
cyan = "#87afaf"
white = "#e4e4e4"

[colors.bright]
black = "#5e5e5e"
red = "#FF5252"
green = "#afaf87"
yellow = "#d8af5f"
blue = "#87afaf"
magenta = "#af87af"
cyan = "#87afaf"
white = "#e4e4e4"
