font_family JetBrains Mono
font_size 11.0
window_padding_width 15
window_padding_height 15
background_opacity 0.9

foreground #e4e4e4
background #1e1e1e
selection_foreground #e4e4e4
selection_background #2d2d2d

mark1_foreground #d78787
mark2_foreground #d78787
mark3_foreground #d78787

url_color #af87af

cursor #e4e4e4
cursor_text_color #2a2a2a

active_tab_foreground #e4e4e4
active_tab_background #2a2a2a
inactive_tab_foreground #5e5e5e
inactive_tab_background #2d2d2d

color0 #2d2d2d
color8 #5e5e5e
color1 #d78787
color9 #d78787
color2 #afaf87
color10 #afaf87
color3 #d8af5f
color11 #d8af5f
color4 #87afaf
color12 #87afaf
color5 #af87af
color13 #af87af
color6 #87afaf
color14 #87afaf
color7 #e4e4e4
color15 #e4e4e4
