font_family JetBrains Mono
font_size 16
window_padding_width 15
window_padding_height 15
background_opacity 0.9

foreground #e4e4e4
background #1e1e1e

selection_foreground #e4e4e4
selection_background #2d2d2d

mark1_foreground #F44336
mark2_foreground #F44336
mark3_foreground #F44336
url_color #FF5252

cursor #F44336
cursor_text_color #2a2a2a

active_tab_foreground #e4e4e4
active_tab_background #D32F2F
inactive_tab_foreground #5e5e5e
inactive_tab_background #2d2d2d

color0  #2d2d2d
color1  #F44336
color2  #afaf87
color3  #d8af5f
color4  #87afaf
color5  #af87af
color6  #87afaf
color7  #e4e4e4

color8  #5e5e5e
color9  #FF5252
color10 #afaf87
color11 #d8af5f
color12 #87afaf
color13 #af87af
color14 #87afaf
color15 #e4e4e4