font_family Ubuntu Mono
font_size 14
window_padding_width 15
window_padding_height 15
background_opacity 0.80
text_composition_strategy legacy

foreground #C8D0E0
background #1E1E1E  

cursor #A54E56        
cursor_text_color #1E1E1E
selection_foreground #C4A86F  
selection_background #2E3440  

mark1_foreground #A54E56
mark2_foreground #8FA37D
mark3_foreground #C4A86F

url_color #8FA37D     

active_tab_foreground #D8DEE9
active_tab_background #5A5A5A  
inactive_tab_foreground #808080
inactive_tab_background #2A2A2A

color0  #2A2A2A
color1  #A54E56
color2  #8FA37D
color3  #C4A86F
color4  #808080       
color5  #927C8D
color6  #7AA5B0
color7  #D0D8E8

color8  #3B3B3B
color9  #A54E56
color10 #8FA37D
color11 #C4A86F
color12 #808080
color13 #927C8D
color14 #7AA5B0
color15 #E0E8F0

clipboard_control write-clipboard write-primary
