# You can find more wallpapers in ~/.config/ml4w/wallpapers/
# Run ~/.config/hypr/reload-hyprpaper.sh after changing your wallpaper
preload = /home/staselovich-n/.config/ml4w/wallpapers/dark-anime-girl-with-red-eyes-desktop-wallpaper.jpg
wallpaper = ,/home/staselovich-n/.config/ml4w/wallpapers/dark-anime-girl-with-red-eyes-desktop-wallpaper.jpg
splash = false
