#  _                      _            _    
# | |__  _   _ _ __  _ __| | ___   ___| | __
# | '_ \| | | | '_ \| '__| |/ _ \ / __| |/ /
# | | | | |_| | |_) | |  | | (_) | (__|   < 
# |_| |_|\__, | .__/|_|  |_|\___/ \___|_|\_\
#        |___/|_|                           
#

background {
    monitor =
    path = ~/.config/ml4w/wallpapers/blue-ichigo.jpg
    color = rgba(46, 52, 64, 0.9)  
    blur_size = 1
    blur_passes = 5
    noise = 0.02
    brightness = 0.8
}

label {
    monitor =
    text = cmd[update:1000]
    color = rgba(216, 222, 233, 0.9)
    font_size = 74
    font_family = Fira Code Nerd Font Bold
    position = 0, 80
    halign = center
    valign = center
    shadow_passes = 3
}
