# Execute your favorite apps at launch
exec-once = hyprpaper
exec-once = hypridle
exec-once = wl-clip-persist --clipboard regular --write-timeout 1000
exec-once = wl-paste --watch cliphist store
exec-once = waybar
exec-once = telegram-desktop -startintray
exec-once = slack -u
