windowrule = match:class clipse, float true # ensure you have a floating window class set if you want this behavior
windowrule = match:class clipse, size 622 652 # set the size of the window as necessary
